version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=icarus

  api:
    build: .
    image: icarus_tracker
    ports:
      - "8080:80"
    environment:
      - DB_PASS=icarus
    links:
      - db:postgres
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
      - ./userscript:/app/static/userscript
    entrypoint: ['/start-reload.sh']
