"""initial migration

Revision ID: 0eb8fa0ff538
Revises: 
Create Date: 2022-01-10 10:54:38.543490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0eb8fa0ff538'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_session',
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.VARCHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('game_session_associations',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('game_session_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'game_session_id')
    )
    op.create_table('marker',
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_session_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'game_session_id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marker')
    op.drop_table('game_session_associations')
    op.drop_table('user')
    op.drop_table('game_session')
    # ### end Alembic commands ###
